<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Automatic</name>
   <tag></tag>
   <elementGuidId>93e07075-d299-4e8c-9322-fa5b32ee01bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[9]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.me-1.btn.btn-outline-primary.btn-md.d-block.w-100</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>77815fb9-cae5-4d07-97fe-ad7756fe5495</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e9b775da-75cb-4754-bb84-a15bd89ba35b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation</name>
      <type>Main</type>
      <value>transmission_input_radio</value>
      <webElementGuid>d6598ae2-6b5c-4929-901b-1ca9ecca1c6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>me-1 btn btn-outline-primary btn-md d-block w-100</value>
      <webElementGuid>b4084acf-4410-4c2b-9e12-488255e198f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Automatic</value>
      <webElementGuid>5ee21044-a7cf-4052-842b-bd3f4b9e69e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;&quot;]/body[@class=&quot;modal-open&quot;]/div[3]/div[1]/div[@class=&quot;modal fade show&quot;]/div[@class=&quot;modal-dialog wrapper wrapper-xs modal-no-shadow&quot;]/div[@class=&quot;modal-content mobile&quot;]/div[@class=&quot;p-0 modal-body&quot;]/div[@class=&quot;wrapper-content container&quot;]/div[@class=&quot;mb-3 d-flex flex-column&quot;]/div[@class=&quot;d-flex&quot;]/button[@class=&quot;me-1 btn btn-outline-primary btn-md d-block w-100&quot;]</value>
      <webElementGuid>b19b89d6-d8cd-43ae-9a96-0f1fe25ec0d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f5568008-eb2d-476a-88a0-073d7038055d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d4ae007c-d935-4145-b09a-7103cf772bfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation</name>
      <type>Main</type>
      <value>transmission_input_radio</value>
      <webElementGuid>83940c65-8dad-4f94-b4c0-6bbeb512ba7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>me-1 btn btn-outline-primary btn-md d-block w-100</value>
      <webElementGuid>12654f5b-a7e2-4808-8062-8af16e5c911f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Automatic</value>
      <webElementGuid>f104db7a-97eb-4f80-8cee-fa6ecb729a9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;&quot;]/body[@class=&quot;modal-open&quot;]/div[5]/div[1]/div[@class=&quot;modal fade show&quot;]/div[@class=&quot;modal-dialog wrapper wrapper-xs modal-no-shadow&quot;]/div[@class=&quot;modal-content mobile&quot;]/div[@class=&quot;p-0 modal-body&quot;]/div[@class=&quot;wrapper-content container&quot;]/div[@class=&quot;mb-3 d-flex flex-column&quot;]/div[@class=&quot;d-flex&quot;]/button[@class=&quot;me-1 btn btn-outline-primary btn-md d-block w-100&quot;]</value>
      <webElementGuid>3af0596b-01c0-4b24-b8a0-51153431a7fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[9]</value>
      <webElementGuid>94cb9cd7-c6c9-4e10-9ee8-efab6b1786ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transmisi'])[1]/following::button[1]</value>
      <webElementGuid>31041bb0-ad2b-4f09-b026-793f337a4719</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Opsional)'])[1]/following::button[1]</value>
      <webElementGuid>748b9d08-7280-4bc1-8d35-62410267882a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manual'])[1]/preceding::button[1]</value>
      <webElementGuid>d465fbc4-d686-4b78-a5be-9ec3e9d16a75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tahun'])[1]/preceding::button[2]</value>
      <webElementGuid>b72ad937-b52b-46b1-8c35-eed76e32ffde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Automatic']/parent::*</value>
      <webElementGuid>651b691e-5fbd-44aa-8600-e9d2a0a43351</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/button</value>
      <webElementGuid>a29bc7d4-5484-4ebe-922a-e03be125a10f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Automatic' or . = 'Automatic')]</value>
      <webElementGuid>a7d5700f-b2fd-4e6c-b617-27cb060cf35c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
