<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Aveo - 1400</name>
   <tag></tag>
   <elementGuidId>9a01bd43-1f33-4da0-9649-faa059d454c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@value='1365']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.car-item.select-search__option</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6fa917f0-71c7-4a46-ba2f-ea508e853bf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>da1c7bd9-ebe9-4a38-a7fb-947dabbfa5d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1365</value>
      <webElementGuid>afceeed9-85ba-4df5-a1f1-848b27120586</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>car-item select-search__option</value>
      <webElementGuid>a0610f76-6a22-4cea-8422-3655c41fe805</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Aveo - 1400</value>
      <webElementGuid>356886c0-62cb-4860-9c5d-45328f1f9aba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;&quot;]/body[@class=&quot;modal-open&quot;]/div[5]/div[1]/div[@class=&quot;modal fade show&quot;]/div[@class=&quot;modal-dialog wrapper wrapper-xs modal-no-shadow&quot;]/div[@class=&quot;modal-content mobile&quot;]/div[@class=&quot;p-0 modal-body&quot;]/div[@class=&quot;wrapper-content container&quot;]/div[@class=&quot;mb-3&quot;]/div[@class=&quot;position-relative&quot;]/div[@class=&quot;select-search select-search--vehicle has-focus&quot;]/div[@class=&quot;select-search__select&quot;]/ul[@class=&quot;select-search__options&quot;]/li[@class=&quot;select-search__row&quot;]/button[@class=&quot;car-item select-search__option&quot;]</value>
      <webElementGuid>08722d56-ae27-4d14-ad3f-3e74e379802b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bbc874a4-70eb-4191-bb76-3b347b8d1580</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>bcffcd9c-b74d-4b4a-ae59-26eba72a5200</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1365</value>
      <webElementGuid>39968523-8261-4194-b051-2f95bef90591</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>car-item select-search__option</value>
      <webElementGuid>dcaf2835-2be5-43c1-95f2-7772e4d806d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Aveo - 1400</value>
      <webElementGuid>00041bc9-12fc-488c-9080-ace6dc303fbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;&quot;]/body[@class=&quot;modal-open&quot;]/div[5]/div[1]/div[@class=&quot;modal fade show&quot;]/div[@class=&quot;modal-dialog wrapper wrapper-xs modal-no-shadow&quot;]/div[@class=&quot;modal-content mobile&quot;]/div[@class=&quot;p-0 modal-body&quot;]/div[@class=&quot;wrapper-content container&quot;]/div[@class=&quot;mb-3&quot;]/div[@class=&quot;position-relative&quot;]/div[@class=&quot;select-search select-search--vehicle has-focus&quot;]/div[@class=&quot;select-search__select&quot;]/ul[@class=&quot;select-search__options&quot;]/li[@class=&quot;select-search__row&quot;]/button[@class=&quot;car-item select-search__option&quot;]</value>
      <webElementGuid>4a279da3-2f6a-4c6c-b544-6e1a0867d82b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@value='1365']</value>
      <webElementGuid>46f5793e-c0f4-4f79-a2dc-1d6744d0f1a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cari Mobil Kamu'])[1]/following::button[1]</value>
      <webElementGuid>3f50367a-1d80-4105-9746-956f02a38733</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mobilku'])[2]/following::button[1]</value>
      <webElementGuid>f31ac110-f6ab-4c64-9caf-8a43aa8a8f6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aveo - 1500'])[1]/preceding::button[1]</value>
      <webElementGuid>5f12347e-dc34-4229-a247-54e468a376b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/div[2]/div[2]/div/div/div/div[2]/ul/li/button</value>
      <webElementGuid>fbab5898-04a9-48a9-a98e-aafdaaf1dce6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Aveo - 1400' or . = 'Aveo - 1400')]</value>
      <webElementGuid>a80721f7-f7f4-47c7-8b76-238425a150a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
