<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Tambah Mobil</name>
   <tag></tag>
   <elementGuidId>90427a2f-8bdd-4788-838d-75f596348287</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='button_add_car']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#button_add_car</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c6f7f87f-ca4c-471f-b389-ac4391b0fdd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>fa82a1f9-591e-4a4c-9448-3452d394c2f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button_add_car</value>
      <webElementGuid>94fd03f4-47b7-4af4-a6a5-d7bed2572412</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation</name>
      <type>Main</type>
      <value>button_add_car</value>
      <webElementGuid>db76e761-7920-4a05-b13c-2709e1f4c9ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-3 btn btn-primary btn-md d-block w-100</value>
      <webElementGuid>520f5904-b4d6-4305-a04b-cb1caddc6d0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tambah Mobil</value>
      <webElementGuid>bd4b2a09-9b7b-4694-9fc7-8ba9870aa217</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button_add_car&quot;)</value>
      <webElementGuid>bb1968c1-4fed-43af-baa4-5b875059f0a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3eb15d8b-51c2-428c-9aea-303f8b7339cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>20b3fa6c-8e92-4fd2-9b49-94083c68bf65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button_add_car</value>
      <webElementGuid>33cce2b9-02a9-453a-a933-43add53ede84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation</name>
      <type>Main</type>
      <value>button_add_car</value>
      <webElementGuid>e75f6068-69ce-473e-bb93-76a4aed798b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-3 btn btn-primary btn-md d-block w-100</value>
      <webElementGuid>4f6aefab-8657-4a53-bdac-ccda4d664853</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tambah Mobil</value>
      <webElementGuid>6e1077a3-1e46-4bd5-88fb-a1877e01b882</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button_add_car&quot;)</value>
      <webElementGuid>752d457d-e25b-49d3-ba67-4bbd75a1be26</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='button_add_car']</value>
      <webElementGuid>d9738bb5-ba58-46ef-b43d-0638b172f3c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tahun'])[1]/following::button[1]</value>
      <webElementGuid>25291530-7d37-4f9c-90a4-755077cb8d87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manual'])[1]/following::button[1]</value>
      <webElementGuid>0333fe8d-b2e8-43f3-b6ea-569ac5acf45c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tambah Mobil']/parent::*</value>
      <webElementGuid>69a4189a-58fe-430e-aaa9-919d0eac4aa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>3b594b2d-3fae-4088-ac71-7a13c8741b06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'button_add_car' and (text() = 'Tambah Mobil' or . = 'Tambah Mobil')]</value>
      <webElementGuid>3e2791fd-cf41-4803-af3e-fc6908e61ffa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
