<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(Opsional)_license-plate-suffix</name>
   <tag></tag>
   <elementGuidId>2092163b-833d-419b-8463-424bc801195f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='license-plate-suffix']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;license-plate-suffix&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5459f56e-64c6-40f6-923e-2de1aa81b6a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>license-plate-suffix</value>
      <webElementGuid>5bd3c804-3be1-4791-9068-f1da0340b913</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>REF</value>
      <webElementGuid>320ba329-776c-4003-abff-033031614580</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>8fd91bdd-4a50-48b9-ab4d-e48d60d31fd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation</name>
      <type>Main</type>
      <value>license_plate_suffix_input</value>
      <webElementGuid>3bdf634e-00a7-4edf-851b-5225ea6adb39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b2acbd2b-1cff-4c77-8de3-6e2c078067fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-center w-25 p-3 form-control</value>
      <webElementGuid>4f54cf6c-d763-40b3-94eb-801a717c61c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;&quot;]/body[@class=&quot;modal-open&quot;]/div[3]/div[1]/div[@class=&quot;modal fade show&quot;]/div[@class=&quot;modal-dialog wrapper wrapper-xs modal-no-shadow&quot;]/div[@class=&quot;modal-content mobile&quot;]/div[@class=&quot;p-0 modal-body&quot;]/div[@class=&quot;wrapper-content container&quot;]/div[@class=&quot;mb-3&quot;]/div[@class=&quot;d-flex license-plate-block&quot;]/input[@class=&quot;text-center w-25 p-3 form-control&quot;]</value>
      <webElementGuid>5609c14e-1607-4740-9bd4-94af43ee2a2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>100df359-b917-4212-b8eb-cfc95f3878cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>license-plate-suffix</value>
      <webElementGuid>31982ae7-1458-4a73-95b6-4d003bc42f99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>REF</value>
      <webElementGuid>c1247c78-fb06-4b44-bc80-ed2adc425335</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>600a4c57-cec3-4e92-8216-380044d41dba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation</name>
      <type>Main</type>
      <value>license_plate_suffix_input</value>
      <webElementGuid>21f287f6-b75a-4ee7-b1d1-6a909c5b388c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7b1d248a-48eb-4905-adc8-cf4db67e5759</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-center w-25 p-3 form-control</value>
      <webElementGuid>e0e8ee7c-96db-47b7-bb90-2ff91ed6db2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;&quot;]/body[@class=&quot;modal-open&quot;]/div[5]/div[1]/div[@class=&quot;modal fade show&quot;]/div[@class=&quot;modal-dialog wrapper wrapper-xs modal-no-shadow&quot;]/div[@class=&quot;modal-content mobile&quot;]/div[@class=&quot;p-0 modal-body&quot;]/div[@class=&quot;wrapper-content container&quot;]/div[@class=&quot;mb-3&quot;]/div[@class=&quot;d-flex license-plate-block&quot;]/input[@class=&quot;text-center w-25 p-3 form-control&quot;]</value>
      <webElementGuid>fef7f7d6-1be3-4f36-8a4e-bf76dc7f3301</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='license-plate-suffix']</value>
      <webElementGuid>873238b8-6099-4539-bb65-acbeacffc41f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[3]</value>
      <webElementGuid>fa772c8e-c3d6-480d-acd9-cf7e6ab5a1d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'license-plate-suffix' and @placeholder = 'REF' and @type = 'text']</value>
      <webElementGuid>aa1a70dc-f582-46c7-b3c3-62e59dcf62b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
